version: '3.9'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    build: .
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/app
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    ports:
      - "3000:3000"

  cron:
    build: .
    command: ["node", "scripts/renewal.js"]
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql-data:
